version: "3.7"
services:
  www:
    build: docker/nginx
    restart: unless-stopped
    volumes:
      - $PWD:/app
      - $PWD/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    ports:
      - "8888:80"
      - "443:443"

  php:
    build: docker/php-fpm
    restart: unless-stopped
    working_dir: /app
    volumes:
      - $PWD:/app

  maildev:
    image: maildev/maildev
    restart: unless-stopped
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8081:80"

  db:
    image: mysql
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "ve"

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      PMA_HOST: db

volumes:
  db:
